#pragma once

#define LED_PIN 13

#define RIGHT_MOTOR_PWM_PIN 7
#define RIGHT_MOTOR_DIR_1_PIN 4
#define RIGHT_MOTOR_DIR_2_PIN 5

#define LEFT_MOTOR_PWM_PIN 6
#define LEFT_MOTOR_DIR_1_PIN 2
#define LEFT_MOTOR_DIR_2_PIN 3

#define LEFT_HRC_TRIG_PIN 48
#define LEFT_HRC_ECHO_PIN 49

#define FRONT_LEFT_HRC_TRIG_PIN 52
#define FRONT_LEFT_HRC_ECHO_PIN 53

#define FRONT_RIGHT_HRC_TRIG_PIN 50
#define FRONT_RIGHT_HRC_ECHO_PIN 51

#define RIGHT_HRC_TRIG_PIN 46
#define RIGHT_HRC_ECHO_PIN 47

#define SERIAL_BAUDRATE 115200

#define TX_BUFFER_SIZE 128
#define RX_BUFFER_SIZE 128
